Smooth Cache Updates for Access Token Providers #59
oracle/ojdbc-extensions pull request #87
Opened 2024-06-10 14:23 UTC by ayouballali

Use the **Oracle JDBC Driver implementation of  caching**  JWTs, instead of the standard **CachedResourceFactory** .This cache is designed for "smooth" updates when a token expires.  this cache uses a background thread to begin requesting a new token at _one minute_ before the current token expires. If the request completes within 30 seconds (which is almost always the case), then threads will not become blocked. Unlike CachedResourceFactory will _block the thread_ while it requests a new token.

This Pr contain also test to verify if that thread will be blocked or not , and verify how much it would take to request a token after it expires . 

**issue :** #59 

**note** : I aded  some  new dependencies for testing and jwt generating :Mockito,JJWT

2024-06-10 20:11 UTC, Michael-A-McMahon requested changes
This looks like a really good start, but we'll need to think about those tricky multi-threaded cases before merging :)
Please reach out to me if you'd like to work out the solution in more detail.

2024-06-10 20:11 UTC, Michael-A-McMahon commented on ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/oauth/AccessTokenFactoryTest.java
> +@RunWith(MockitoJUnitRunner.class)
The test suite for Oracle JDBC will verify the access token cache. There are tests to make sure that it executes updates and blocks threads at the correct times. 

We should delete this new test because it's mostly verifying code in Oracle JDBC, and not verifying code in the provider.

To verify code in the provider, we need to add these tests:
1. Spawn many threads, maybe 16-32. Have each thread request a token using the same parameters. Have the threads request the token 100 times in a loop. On each iteration of the loop, have the thread verify that the same instance of AccessToken is returned, as in `previousToken == nextToken`. After the 100th iteration, have the main thread verify that all child threads got the same instance of AccessToken. CompletableFuture might be helpful for having child threads return a result to the main thread. I think this test will fail because there's no thread safety in the `if (tokenCache == null)` check. Many threads can see a null tokenCache, and then many threads will create a new cache and assign it to that field.
2. Request a token with the SCOPE parameter set to some value, X. Request a token again with the SCOPE parameter set to a different value, Y. Verify that the same token is not returned for both requests. I think this test will fail because the factories retain a single tokenCache which requests a token using the first parameter set.

Both problems are ones that the CachedResourceFactory solves. It prevents more than one thread from allocating a resource for the same parameter set. And, it keys resources based on their parameter set. What if we had a `CachedResourceFactory<Supplier<AccessToken>>`? Would that get us anywhere?

2024-06-10 20:11 UTC, Michael-A-McMahon commented on ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/oauth/AccessTokenFactory.java
> +  private static ResourceFactory<AccessToken> INSTANCE = new AccessTokenFactory();
This field should be `final`. This class is implementing a singleton pattern, so we don't want to instantiate AccessTokenFactory more than once.

2024-06-19 19:35 UTC, ayouballali commented
Now we are relying on CachedResourceFactory<Supplier<AccessToken>> to cache token  supplier per each parameter set instead of caching the token itself . so the _request()_ method of **AccessTokenFactory** now returns Supplier<AccessToken> , and the driver's cache will handle caching the tokens .

I added tests to make sure that this mechanism is thread safe also to verify the uniqueness of tokens per parameter set .

2024-06-22 00:36 UTC, Michael-A-McMahon commented on ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/oauth/AccessTokenFactory.java
> +  private static final   ResourceFactory<Supplier<?extends AccessToken>> INSTANCE = CachedResourceFactory.create(new AccessTokenFactory());
Our code uses 80 character line limits, and we usually put a space after "?" in a generic type declaration. Please try to keep your code style consistent where you can.

Personally, I think whitespace is the least important thing about code. I usually won't waste everyone's time by commenting about it. I mentioning this only because, eventually, you will encounter a code review where it's treated like a big deal. So it's good to get into the practice of learning the existing code style and trying to replicate it.

2024-06-22 01:23 UTC, Michael-A-McMahon commented
Awesome: Looks like the Supplier-as-a-resource design is working out.

mockito and the jwt lib need to go. I'll bet that with just a little bit of code, you can solve the same problems that you're using these libraries to solve. This would be preferable because a few lines of code is much easier to understand than the API and source code of these libraries. 
I don't have much experience working with these libraries, and I don't know if other programmers on this project do either. When you introduce a new library into a code base, you are forcing everyone else who works on that code to also have learn how that library works. If the only benefit of the library is you not having to write a bit of code, then this doesn't feel like a good trade off :)

In any case, we need to replace mock-ups with integration tests. That is, we need tests that actually request tokens from Azure and OCI. Our test suite is already designed to do this, so you can look to existing tests for examples. 
We really favor integration testing over mock-ups because at the end of the day, our users need this code to work correctly with cloud services. Mock classes won't provide that level of verification. I think you can hit all the cases you're wanting to test without needing to mock a token request.

2024-07-09 23:36 UTC, Michael-A-McMahon commented on ojdbc-provider-common/src/test/java/oracle/jdbc/provider/TestProperties.java
> +    "example-test.properties"))
We should leave the default as "test.properties". The example-test.properties file is meant to be copied to a new file named "test.properties". And the "test.properties" file is in our .gitignore file. The idea is that test.properties could contain security sensitive info, so we never want to accidentally push it on to GitHub for the whole world to see. However, example-test.properties is being pushed to GitHub, so we definitely don't want any code that would read actual information from this example file.

2024-07-09 23:41 UTC, Michael-A-McMahon reviewed
Thanks for all the effort on making these revisions. I really appreciate it.
Only thing left is the default test.properties location. I can approve after that change is reverted. We can discuss more if needed.

2024-07-12 17:36 UTC, Michael-A-McMahon submitted a review, later dismissed
Ready to merge! Thanks again for all your work on this. I hope you'll get more opportunities to contribute to this project.

2024-07-19 09:34 UTC, jeandelavarene commented on ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/oauth/AccessTokenFactoryTest.java
> +    private CachedResourceFactory<Supplier<?extends AccessToken>> cachedResourceFactory;
Can you please change the indentation to 2 space chars?

2024-07-19 09:35 UTC, jeandelavarene commented on ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/oauth/AccessTokenFactoryTest.java
> +public class AccessTokenFactoryTest {
Please add a JavaDoc comment that explains what this class does.

2024-07-19 09:44 UTC, jeandelavarene commented
Please add a documentation note in the "Access Token Provider" section of both OCI and Azure and explain how tokens are cached. You can provide a link to the javadoc:
https://docs.oracle.com/en//database/oracle/oracle-database/23/jajdb/oracle/jdbc/AccessToken.html#createJsonWebTokenCache(java.util.function.Supplier)

2024-08-01 22:20 UTC, Michael-A-McMahon submitted a review, later dismissed
This is great, thanks!

2024-08-19 21:40 UTC, Michael-A-McMahon commented
The latest commit reworks the solution a bit:
- The existing AccessTokenFactory classes remain unchanged
- A new AccessTokenCacheFactory delegates to the existing AccessTokenFactory implementations. This new factory resides in the common module because it is not specific to OCI or Azure. It interfaces with the ResourceFactory<AccessToken> abstraction.
- The existing tests were consolidated into a single test. The single test verifies the AccessTokenCacheFactory using a mock ResourceFactory<AccessToken>
- The existing tests were converted to JUnit 5.
- Unused dependencies on JWT library and Mockito were removed from the pom.xml files

2024-08-20 18:26 UTC, Michael-A-McMahon approved these changes

2024-08-20 18:27 UTC, merged